In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('games_2007_2020.csv')

c:\users\rubaz\projects\crossdata\ds_crossdata\cf_project\lib\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (0,19) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [5]:
df

,overallScore,overallRank,countryChampion,countryOfOriginName,countryOfOriginCode,affiliateName,firstName,lastName,competitorName,competitorId,...,mobileScoreDisplay,rank,heat,points,scoreDisplay,time,workoutrank,division,year,competitionType
0,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"13:39, 95 pts",2,0.0,95,13:39,13:39,2,1,2007,games
1,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"20:45, 95 pts",2,0.0,95,20:45,20:45,2,1,2007,games
2,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"906.4 lb, 82 pts",11,0.0,82,906.4 lb,906.4,11,1,2007,games
3,270,2,False,NaN,NaN,NaN,Brett,Marshall,Brett Marshall,57785.0,...,"13:07, 100 pts",1,0.0,100,13:07,13:07,1,1,2007,games
4,270,2,False,NaN,NaN,NaN,Brett,Marshall,Brett Marshall,57785.0,...,"22:00, 90 pts",3,0.0,90,22:00,22:00,3,1,2007,games
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36551,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,NaN,CUT,0.0,0,NaN,NaN,CUT,2,2019,games
36552,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,NaN,CUT,0.0,0,NaN,NaN,CUT,2,2019,games
36553,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,NaN,CUT,0.0,0,NaN,NaN,CUT,2,2019,games
36554,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,NaN,CUT,0.0,0,NaN,NaN,CUT,2,2019,games
36555,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,NaN,CUT,0.0,0,NaN,NaN,CUT,2,2019,games

In [12]:
#Keep division 1 and 2 only
df_div = df[(df['division'] == 1) | (df['division'] == 2)]

In [22]:
#convert column competitorName to str
df_div['competitorName'] = df_div['competitorName'].astype(str)

<ipython-input-22-43ae1795e4b6>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_div['competitorName'] = df_div['competitorName'].astype(str)

In [26]:
#Remove Duplicates
df_div = df_div.drop_duplicates(['competitorName', 'year'])

In [27]:
df_div

,overallScore,overallRank,countryChampion,countryOfOriginName,countryOfOriginCode,affiliateName,firstName,lastName,competitorName,competitorId,...,mobileScoreDisplay,rank,heat,points,scoreDisplay,time,workoutrank,division,year,competitionType
0,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"13:39, 95 pts",2,0.0,95,13:39,13:39,2,1,2007,games
3,270,2,False,NaN,NaN,NaN,Brett,Marshall,Brett Marshall,57785.0,...,"13:07, 100 pts",1,0.0,100,13:07,13:07,1,1,2007,games
6,267,3,False,NaN,NaN,NaN,Josh,Everett,Josh Everett,10091.0,...,"14:13, 89 pts",4,0.0,89,14:13,14:13,4,1,2007,games
9,261,4,False,NaN,NaN,NaN,Chris,Spealler,Chris Spealler,27065.0,...,"13:52, 90 pts",3,0.0,90,13:52,13:52,3,1,2007,games
12,48,1,False,NaN,NaN,NaN,Graham,Holmberg,Graham Holmberg,262945.0,...,"4:33, 11 pts",11,0.0,11,4:33,4:33,11,1,2010,games
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36496,-42.0,125,False,Botswana,BW,CrossFit Gaborone,Cingiwe Ciegy,Seru,Cingiwe Ciegy Seru,1218177.0,...,"CAP+43, -42 pts",117T,1.0,-42,CAP+43,CAP+43,117T,2,2019,games
36508,-42.0,126,False,Andorra,AD,La Borda CrossFit,Miriam,Torra,Miriam Torra Sola,1243131.0,...,"CAP+43, -42 pts",117T,1.0,-42,CAP+43,CAP+43,117T,2,2019,games
36520,-42.0,127,False,Serbia,RS,NaN,Tamara,Trumbetaš,Tamara Trumbetaš,1521928.0,...,"CAP+43, -42 pts",117T,1.0,-42,CAP+43,CAP+43,117T,2,2019,games
36532,-42.0,128,False,Sri Lanka,LK,CrossFit Ceylon,Keshini,Vitharana,Keshini Vitharana,661943.0,...,"CAP+43, -42 pts",117T,1.0,-42,CAP+43,CAP+43,117T,2,2019,games
36544,-42.0,129,False,Mauritius,MU,UPT CrossFit,Melanie,Yip Woon Sun,Melanie Yip Woon Sun,889971.0,...,"CAP+43, -42 pts",117T,1.0,-42,CAP+43,CAP+43,117T,2,2019,games

In [29]:
df_div[df_div['year'] == 2007]

,overallScore,overallRank,countryChampion,countryOfOriginName,countryOfOriginCode,affiliateName,firstName,lastName,competitorName,competitorId,...,mobileScoreDisplay,rank,heat,points,scoreDisplay,time,workoutrank,division,year,competitionType
0,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"13:39, 95 pts",2,0.0,95,13:39,13:39,2,1,2007,games
3,270,2,False,NaN,NaN,NaN,Brett,Marshall,Brett Marshall,57785.0,...,"13:07, 100 pts",1,0.0,100,13:07,13:07,1,1,2007,games
6,267,3,False,NaN,NaN,NaN,Josh,Everett,Josh Everett,10091.0,...,"14:13, 89 pts",4,0.0,89,14:13,14:13,4,1,2007,games
9,261,4,False,NaN,NaN,NaN,Chris,Spealler,Chris Spealler,27065.0,...,"13:52, 90 pts",3,0.0,90,13:52,13:52,3,1,2007,games
13,252,5,False,NaN,NaN,NaN,Breck,Berry,Breck Berry,7173.0,...,"18:21, 80 pts",13,0.0,80,18:21,18:21,13,1,2007,games
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2144,121,39,False,NaN,NaN,NaN,Saul,Jimenez,Saul Jimenez,41231.0,...,"19:28 Jumping Pullups, 55 pts",38,0.0,55,19:28 Jumping Pullups,19:28 Jumping Pullups,38,1,2007,games
2206,85,40,False,NaN,NaN,NaN,Zac,Pine,Zac Pine,97943.0,...,"16:55, 85 pts",8,0.0,85,16:55,16:55,8,1,2007,games
2294,59,41,False,NaN,NaN,NaN,Russell,Bruel,Russell Bruel,82637.0,...,"19:29 95#, 59 pts",34,0.0,59,19:29 95#,19:29 95#,34,1,2007,games
2470,85,43,False,NaN,NaN,NaN,Jacob,Typskin,Jacob Typskin,NaN,...,NaN,WD,0.0,0,NaN,NaN,WD,1,2007,games
2566,56,44,False,NaN,NaN,NaN,Keegan,Martin,Keegan Martin,27667.0,...,NaN,WD,0.0,0,NaN,NaN,WD,1,2007,games

In [ ]:
#parsing column overallRank

#df_div['overallRank'] = df_div['overallRank'].astype(int)

In [37]:
pd.set_option('display.max_rows', 5000)
df_div['overallRank'].value_counts()

15          28
2           28
3           28
5           28
8           28
13          28
12          28
7           28
6           28
10          28
18          28
16          28
20          28
9           28
14          28
11          28
19          28
1           28
17          28
4           28
28          27
23          27
21          27
29          27
26          27
24          27
22          27
27          27
25          27
30          27
32          25
35          25
36          25
33          25
31          25
34          25
37          24
38          24
39          23
40          21
41          16
42          15
43          15
44          13
45          11
46           9
47           7
48           6
49           6
DQ           6
69           5
53           5
62           5
70           5
67           5
56           5
52           5
57           5
50           5
66           5
63           5
60           5
58           5
65           5
61           5
59           5
54           5
64           5
68           5
55           5
51           5
73           4
71           4
72           4
74           4
--           4
91           3
112          3
95           3
97           3
86           3
117          3
104          3
83           3
116          3
96           3
85           3
82           3
94           3
77           3
78           3
107          3
79           3
76           3
115          3
103          3
90           3
99           3
80           3
113          3
105          3
108          3
92           3
102          3
111          3
98           3
87           3
118          3
84           3
119          3
89           3
106          3
109          3
88           3
114          3
93           3
110          3
75           3
100          3
101          3
81           3
123          2
120          2
127          2
129          2
126          2
121          2
128          2
44T          2
122          2
125          2
71 (DNS)     2
124          2
136          1
130          1
135          1
137          1
131          1
134          1
138          1
139          1
132          1
133          1
140          1
141          1
Name: overallRank, dtype: int64

In [39]:
df_div['overallRank'].filter(regex=r'\D')

Series([], Name: overallRank, dtype: object)

In [41]:
df_div[df_div['overallRank'] == '1']

,overallScore,overallRank,countryChampion,countryOfOriginName,countryOfOriginCode,affiliateName,firstName,lastName,competitorName,competitorId,...,mobileScoreDisplay,rank,heat,points,scoreDisplay,time,workoutrank,division,year,competitionType
0,272,1,False,NaN,NaN,NaN,James,Fitzgerald,James Fitzgerald,164070.0,...,"13:39, 95 pts",2,0.0,95,13:39,13:39,2,1,2007,games
12,48,1,False,NaN,NaN,NaN,Graham,Holmberg,Graham Holmberg,262945.0,...,"4:33, 11 pts",11,0.0,11,4:33,4:33,11,1,2010,games
16,915,1,False,United States,US,CrossFit Krypton,Ben,Smith,Ben Smith,43761.0,...,"49:20.51, 72 pts",7,1.0,72,49:20.51,49:20.51,7,1,2015,games
18,856,1,False,United States,US,NaN,Rich,Froning,Rich Froning,11435.0,...,"41:33.0, 35 pts",26,0.0,35,41:33.0,41:33.0,26,1,2011,games
23,1089,1,False,NaN,NaN,CrossFit Faith,Richard,Froning Jr.,Rich Froning,11435.0,...,"48:59.0, 51 pts",18,NaN,51,48:59.0,48:59.0,18,1,2012,games
27,78,1,False,NaN,NaN,NaN,Mikko,Salo,Mikko Salo,151906.0,...,"37:44.6, 2 pts",2,0.0,2,37:44.6,37:44.6,2,1,2009,games
36,925,1,False,NaN,NaN,CrossFit Mayhem,Richard,Froning Jr.,Rich Froning,11435.0,...,"35:10.11, 71 pts",8,1.0,71,35:10.11,35:10.11,8,1,2014,games
37,13:17.0,1,False,NaN,NaN,NaN,Jason,Khalipa,Jason Khalipa,12485.0,...,3:56.0,11,0.0,NaN,3:56.0,3:56.0,11,1,2008,games
43,962,1,False,NaN,NaN,CrossFit Mayhem,Richard,Froning Jr.,Rich Froning,11435.0,...,"14:02.1, 27 pts",30,3.0,27,14:02.1,14:02.1,30,1,2013,games
70,290,1,False,NaN,NaN,NaN,Jolie,Gentry,Jolie Gentry,NaN,...,"16:22, 100 pts",1,0.0,100,16:22,16:22,1,2,2007,games
86,19:10.0,1,False,NaN,NaN,NaN,Caity,Matter,Caity Matter,8335.0,...,6:58.0,8,0.0,NaN,6:58.0,6:58.0,8,2,2008,games
106,1132,1,NaN,NaN,NaN,2080,Mathew,Fraser,Mathew Fraser,153604.0,...,"29:40.50, 72 pts",7,1.0,72,29:40.50,29:40.50,7,1,2017,games
131,1096,1,False,United States,US,Champlain Valley CrossFit,Mathew,Fraser,Mathew Fraser,153604.0,...,"34:10.27, 100 pts",1,1.0,100,34:10.27,34:10.27,1,1,2016,games
136,1162,1,NaN,NaN,US,CrossFit Mayhem,Mathew,Fraser,Mat Fraser,153604.0,...,"18:36.55, 84 pts",4,1.0,84,18:36.55,18:36.55,4,1,2018,games
172,1150,1,False,United States,US,CrossFit Mayhem,Mathew,Fraser,Mathew Fraser,153604.0,...,"3:08, 100 pts",1,1.0,100,3:08,3:08,1,1,2020,games
190,31,1,False,NaN,NaN,NaN,Kristan,Clever,Kristan Clever,36734.0,...,"5:04, 1 pts",1,0.0,1,5:04,5:04,1,2,2010,games
191,54,1,False,NaN,NaN,NaN,Tanya,Wagner,Tanya Wagner,57509.0,...,"46:17.0, 11 pts",11,0.0,11,46:17.0,46:17.0,11,2,2009,games
229,842,1,False,Iceland,IS,NaN,Annie,Thorisdottir,Annie Thorisdottir,18588.0,...,"43:12.0, 80 pts",5,0.0,80,43:12.0,43:12.0,5,2,2011,games
283,1062,1,False,NaN,NaN,CrossFit Reykjavík,Annie,Thorisdottir,Annie Thorisdottir,18588.0,...,"53:58.0, 55 pts",16,NaN,55,53:58.0,53:58.0,16,2,2012,games
304,920,1,False,NaN,NaN,CrossFit Black Five,Samantha,Briggs,Samantha Briggs,2536.0,...,"14:16.4, 85 pts",4,3.0,85,14:16.4,14:16.4,4,2,2013,games
307,918,1,False,NaN,NaN,CrossFit Brossard,Camille,Leblanc-Bazinet,Camille Leblanc-Bazinet,8404.0,...,"35:58.54, 75 pts",6,1.0,75,35:58.54,35:58.54,6,2,2014,games
333,790,1,False,Iceland,IS,CrossFit Reykjavík,Katrin Tanja,Davidsdottir,Katrin Tanja Davidsdottir,55121.0,...,"54:30.08, 44 pts",18,1.0,44,54:30.08,54:30.08,18,2,2015,games
359,994,1,NaN,NaN,NaN,13770,Tia-Clair,Toomey,Tia-Clair Toomey,163097.0,...,"28:45.65, 100 pts",1,1.0,100,28:45.65,28:45.65,1,2,2017,games
383,984,1,False,United States,US,CrossFit New England,Katrin Tanja,Davidsdottir,Katrin Tanja Davidsdottir,55121.0,...,"38:27.21, 84 pts",4,1.0,84,38:27.21,38:27.21,4,2,2016,games
440,984,1,False,United States,US,CrossFit Mayhem,Mathew,Fraser,Mathew Fraser,153604.0,...,"15:07.70, 100 pts",1,3.0,100,15:07.70,15:07.70,1,1,2019,games
443,1154,1,NaN,NaN,AU,CrossFit Gladstone,Tia-Clair,Toomey,Tia-Clair Toomey,163097.0,...,"20:02.79, 80 pts",5,1.0,80,20:02.79,20:02.79,5,2,2018,games
12562,1025,1,False,Australia,AU,CrossFit Mayhem,Tia-Clair,Toomey,Tia-Clair Toomey,163097.0,...,"3:40, 100 pts",1,1.0,100,3:40,3:40,1,2,2020,games
12713,1071,1,False,Australia,AU,CrossFit Mayhem,Tia-Clair,Toomey,Tia-Clair Toomey,163097.0,...,"16:56.63, 100 pts",1,3.0,100,16:56.63,16:56.63,1,2,2019,games